services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_APP_URL=http://localhost:3000
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
        - NEON_AUTH_COOKIE_SECRET=${NEON_AUTH_COOKIE_SECRET}
        - NEON_AUTH_BASE_URL=${NEON_AUTH_BASE_URL}
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend


# add docker compose to run all the app in just one comand and terminal